// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: question_form_updater.proto

package question_form_updater_v1

import (
	question_v1 "github.com/Kosfedev/learn_go/pkg/question_v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWithOptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *CreateWithOptionsRequest_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateWithOptionsRequest) Reset() {
	*x = CreateWithOptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWithOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithOptionsRequest) ProtoMessage() {}

func (x *CreateWithOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithOptionsRequest.ProtoReflect.Descriptor instead.
func (*CreateWithOptionsRequest) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWithOptionsRequest) GetData() *CreateWithOptionsRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateWithOptionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateWithOptionsResponse) Reset() {
	*x = CreateWithOptionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWithOptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithOptionsResponse) ProtoMessage() {}

func (x *CreateWithOptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithOptionsResponse.ProtoReflect.Descriptor instead.
func (*CreateWithOptionsResponse) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWithOptionsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddSubcategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionId     int64   `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SubcategoryIds []int64 `protobuf:"varint,2,rep,packed,name=subcategory_ids,json=subcategoryIds,proto3" json:"subcategory_ids,omitempty"`
}

func (x *AddSubcategoriesRequest) Reset() {
	*x = AddSubcategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSubcategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubcategoriesRequest) ProtoMessage() {}

func (x *AddSubcategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubcategoriesRequest.ProtoReflect.Descriptor instead.
func (*AddSubcategoriesRequest) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{2}
}

func (x *AddSubcategoriesRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AddSubcategoriesRequest) GetSubcategoryIds() []int64 {
	if x != nil {
		return x.SubcategoryIds
	}
	return nil
}

type AddSubcategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddSubcategoriesResponse) Reset() {
	*x = AddSubcategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSubcategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubcategoriesResponse) ProtoMessage() {}

func (x *AddSubcategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubcategoriesResponse.ProtoReflect.Descriptor instead.
func (*AddSubcategoriesResponse) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{3}
}

type RemoveSubcategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionId     int64   `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SubcategoryIds []int64 `protobuf:"varint,2,rep,packed,name=subcategory_ids,json=subcategoryIds,proto3" json:"subcategory_ids,omitempty"`
}

func (x *RemoveSubcategoriesRequest) Reset() {
	*x = RemoveSubcategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSubcategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubcategoriesRequest) ProtoMessage() {}

func (x *RemoveSubcategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubcategoriesRequest.ProtoReflect.Descriptor instead.
func (*RemoveSubcategoriesRequest) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveSubcategoriesRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *RemoveSubcategoriesRequest) GetSubcategoryIds() []int64 {
	if x != nil {
		return x.SubcategoryIds
	}
	return nil
}

type RemoveSubcategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveSubcategoriesResponse) Reset() {
	*x = RemoveSubcategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSubcategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubcategoriesResponse) ProtoMessage() {}

func (x *RemoveSubcategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubcategoriesResponse.ProtoReflect.Descriptor instead.
func (*RemoveSubcategoriesResponse) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{5}
}

type AddSetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionId int64   `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SetIds     []int64 `protobuf:"varint,2,rep,packed,name=set_ids,json=setIds,proto3" json:"set_ids,omitempty"`
}

func (x *AddSetsRequest) Reset() {
	*x = AddSetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSetsRequest) ProtoMessage() {}

func (x *AddSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSetsRequest.ProtoReflect.Descriptor instead.
func (*AddSetsRequest) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{6}
}

func (x *AddSetsRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AddSetsRequest) GetSetIds() []int64 {
	if x != nil {
		return x.SetIds
	}
	return nil
}

type AddSetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddSetsResponse) Reset() {
	*x = AddSetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSetsResponse) ProtoMessage() {}

func (x *AddSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSetsResponse.ProtoReflect.Descriptor instead.
func (*AddSetsResponse) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{7}
}

type RemoveSetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuestionId int64   `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	SetIds     []int64 `protobuf:"varint,2,rep,packed,name=set_ids,json=setIds,proto3" json:"set_ids,omitempty"`
}

func (x *RemoveSetsRequest) Reset() {
	*x = RemoveSetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSetsRequest) ProtoMessage() {}

func (x *RemoveSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSetsRequest.ProtoReflect.Descriptor instead.
func (*RemoveSetsRequest) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveSetsRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *RemoveSetsRequest) GetSetIds() []int64 {
	if x != nil {
		return x.SetIds
	}
	return nil
}

type RemoveSetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveSetsResponse) Reset() {
	*x = RemoveSetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSetsResponse) ProtoMessage() {}

func (x *RemoveSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSetsResponse.ProtoReflect.Descriptor instead.
func (*RemoveSetsResponse) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{9}
}

type CreateWithOptionsRequest_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question *question_v1.NewQuestion         `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Options  []*question_v1.NewQuestionOption `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
}

func (x *CreateWithOptionsRequest_Data) Reset() {
	*x = CreateWithOptionsRequest_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_question_form_updater_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWithOptionsRequest_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWithOptionsRequest_Data) ProtoMessage() {}

func (x *CreateWithOptionsRequest_Data) ProtoReflect() protoreflect.Message {
	mi := &file_question_form_updater_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWithOptionsRequest_Data.ProtoReflect.Descriptor instead.
func (*CreateWithOptionsRequest_Data) Descriptor() ([]byte, []int) {
	return file_question_form_updater_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateWithOptionsRequest_Data) GetQuestion() *question_v1.NewQuestion {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *CreateWithOptionsRequest_Data) GetOptions() []*question_v1.NewQuestionOption {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_question_form_updater_proto protoreflect.FileDescriptor

var file_question_form_updater_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x1a, 0x0e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdf, 0x01, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x4b, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x37, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f,
	0x72, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x76, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x08, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x38, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x2e, 0x4e,
	0x65, 0x77, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2b, 0x0a, 0x19, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x63, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x53, 0x75, 0x62,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x75, 0x62,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x41,
	0x64, 0x64, 0x53, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x66, 0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x53, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x0e, 0x73, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x73, 0x22,
	0x1d, 0x0a, 0x1b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4a,
	0x0a, 0x0e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x74, 0x49, 0x64, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4d, 0x0a,
	0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x74, 0x49, 0x64, 0x73, 0x22, 0x14, 0x0a, 0x12,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xde, 0x04, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x6f, 0x72, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x56, 0x31, 0x12, 0x7c, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x32, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f, 0x72,
	0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x79, 0x0a, 0x10, 0x41, 0x64,
	0x64, 0x53, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x31,
	0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x75, 0x62,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x32, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f, 0x72,
	0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64,
	0x53, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x82, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x53, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x34, 0x2e,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53,
	0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66,
	0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x75, 0x62, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x74, 0x73, 0x12, 0x28, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31,
	0x2e, 0x41, 0x64, 0x64, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x67, 0x0a, 0x0a, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x74, 0x73, 0x12, 0x2b, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72,
	0x5f, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x54, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4b, 0x6f, 0x73, 0x66, 0x65, 0x64, 0x65, 0x76, 0x2f, 0x6c, 0x65, 0x61, 0x72, 0x6e,
	0x5f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31,
	0x3b, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_question_form_updater_proto_rawDescOnce sync.Once
	file_question_form_updater_proto_rawDescData = file_question_form_updater_proto_rawDesc
)

func file_question_form_updater_proto_rawDescGZIP() []byte {
	file_question_form_updater_proto_rawDescOnce.Do(func() {
		file_question_form_updater_proto_rawDescData = protoimpl.X.CompressGZIP(file_question_form_updater_proto_rawDescData)
	})
	return file_question_form_updater_proto_rawDescData
}

var file_question_form_updater_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_question_form_updater_proto_goTypes = []interface{}{
	(*CreateWithOptionsRequest)(nil),      // 0: question_form_updater_v1.CreateWithOptionsRequest
	(*CreateWithOptionsResponse)(nil),     // 1: question_form_updater_v1.CreateWithOptionsResponse
	(*AddSubcategoriesRequest)(nil),       // 2: question_form_updater_v1.AddSubcategoriesRequest
	(*AddSubcategoriesResponse)(nil),      // 3: question_form_updater_v1.AddSubcategoriesResponse
	(*RemoveSubcategoriesRequest)(nil),    // 4: question_form_updater_v1.RemoveSubcategoriesRequest
	(*RemoveSubcategoriesResponse)(nil),   // 5: question_form_updater_v1.RemoveSubcategoriesResponse
	(*AddSetsRequest)(nil),                // 6: question_form_updater_v1.AddSetsRequest
	(*AddSetsResponse)(nil),               // 7: question_form_updater_v1.AddSetsResponse
	(*RemoveSetsRequest)(nil),             // 8: question_form_updater_v1.RemoveSetsRequest
	(*RemoveSetsResponse)(nil),            // 9: question_form_updater_v1.RemoveSetsResponse
	(*CreateWithOptionsRequest_Data)(nil), // 10: question_form_updater_v1.CreateWithOptionsRequest.Data
	(*question_v1.NewQuestion)(nil),       // 11: question_v1.NewQuestion
	(*question_v1.NewQuestionOption)(nil), // 12: question_v1.NewQuestionOption
}
var file_question_form_updater_proto_depIdxs = []int32{
	10, // 0: question_form_updater_v1.CreateWithOptionsRequest.data:type_name -> question_form_updater_v1.CreateWithOptionsRequest.Data
	11, // 1: question_form_updater_v1.CreateWithOptionsRequest.Data.question:type_name -> question_v1.NewQuestion
	12, // 2: question_form_updater_v1.CreateWithOptionsRequest.Data.options:type_name -> question_v1.NewQuestionOption
	0,  // 3: question_form_updater_v1.QuestionFormUpdaterV1.CreateWithOptions:input_type -> question_form_updater_v1.CreateWithOptionsRequest
	2,  // 4: question_form_updater_v1.QuestionFormUpdaterV1.AddSubcategories:input_type -> question_form_updater_v1.AddSubcategoriesRequest
	4,  // 5: question_form_updater_v1.QuestionFormUpdaterV1.RemoveSubcategories:input_type -> question_form_updater_v1.RemoveSubcategoriesRequest
	6,  // 6: question_form_updater_v1.QuestionFormUpdaterV1.AddSets:input_type -> question_form_updater_v1.AddSetsRequest
	8,  // 7: question_form_updater_v1.QuestionFormUpdaterV1.RemoveSets:input_type -> question_form_updater_v1.RemoveSetsRequest
	1,  // 8: question_form_updater_v1.QuestionFormUpdaterV1.CreateWithOptions:output_type -> question_form_updater_v1.CreateWithOptionsResponse
	3,  // 9: question_form_updater_v1.QuestionFormUpdaterV1.AddSubcategories:output_type -> question_form_updater_v1.AddSubcategoriesResponse
	5,  // 10: question_form_updater_v1.QuestionFormUpdaterV1.RemoveSubcategories:output_type -> question_form_updater_v1.RemoveSubcategoriesResponse
	7,  // 11: question_form_updater_v1.QuestionFormUpdaterV1.AddSets:output_type -> question_form_updater_v1.AddSetsResponse
	9,  // 12: question_form_updater_v1.QuestionFormUpdaterV1.RemoveSets:output_type -> question_form_updater_v1.RemoveSetsResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_question_form_updater_proto_init() }
func file_question_form_updater_proto_init() {
	if File_question_form_updater_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_question_form_updater_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWithOptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_form_updater_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWithOptionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_form_updater_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSubcategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_form_updater_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSubcategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_form_updater_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSubcategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_form_updater_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSubcategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_form_updater_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_form_updater_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_form_updater_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_form_updater_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_question_form_updater_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWithOptionsRequest_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_question_form_updater_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_question_form_updater_proto_goTypes,
		DependencyIndexes: file_question_form_updater_proto_depIdxs,
		MessageInfos:      file_question_form_updater_proto_msgTypes,
	}.Build()
	File_question_form_updater_proto = out.File
	file_question_form_updater_proto_rawDesc = nil
	file_question_form_updater_proto_goTypes = nil
	file_question_form_updater_proto_depIdxs = nil
}
