# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused
  exclusions:
    rules:
        # protobuf конвертирует id в Id вместо ID, чем триггерит revive
      - path: internal/api
        linters:
          - revive
        # требует публичного типа экспорта pgConfig, grpcConfig - нежелательно
      - path: internal/config/env
        linters:
          - revive