name: pull request
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  Lint:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
      - run: go version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v1.64.5
          args: --config=.golangci.pipeline.yaml